RDKEVD-8621:FBI:add bluetooth in conf/template/bblayers.conf.sample
https://ccp.sys.comcast.net/browse/RDKEVD-8621
---
Need to add meta-rdk-bluetooth in middleware's submanifest rdke-middleware-generic-manifest/middleware-generic.xml
---
avoid following build issue
ERROR: lib32-bluetooth-core-1.0.11-r2 do_compile: oe_runmake failed
ERROR: lib32-bluetooth-core-1.0.11-r2 do_compile: ExecutionError('/home/ubuntu/builds/rdk-e/rdk-yocto-gha-jobs/build-rdktv-us-armv8a/tmp-debug/work/rdktv-us-armv8a-middleware-rdkmllib32-linux-gnueabi/lib32-bluetooth-core/1.0.11-r2/temp/run.do_compile.3921300', 1, None, None)

| ../../git/src/btrCore_avMedia.c:52:10: fatal error: bluetooth/audio/a2dp-codecs.h: No such file or directory
|    52 | #include <bluetooth/audio/a2dp-codecs.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---

Signed-off-by: Vamsi Krishna Palla <vamsikrishna.palla@sky.uk>